namePrefix: demo-

vars:
- name: WORDPRESS_SERVICE
  objref:
    kind: Service
    name: wordpress
    apiVersion: v1
- name: MYSQL_SERVICE
  objref:
    kind: Service
    name: wordpress-mysql
    apiVersion: v1
secretGenerator:
- name: mysql-pass
  literals:
  - password=sql_password
resources:
  - pv1.yaml
  - pv2.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
