apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: vol1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data1
  persistentVolumeReclaimPolicy: Retain
