apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: vol2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data2
  persistentVolumeReclaimPolicy: Retain
